version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../:/var/www/html
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - php-fpm
      
  php-fpm:
    image: nanoninja/php-fpm:7.1.14
    container_name: php-fpm
    restart: always
    volumes:
      - ../:/var/www/html
    links:
      - mysql:docker-db
      - redis:docker-redis
    depends_on:
      - mysql
      - redis
      
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/entrypoint:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: techsight
      MYSQL_DATABASE: ts_statistics_config
      MYSQL_USER: tobuser
      MYSQL_PASSWORD: techsight
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci", "--sql_mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"]
      
  redis:
    image: redis:4.0
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
